CREATE TABLE [dbo].[ResultData]
(
	[ResId] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[Score] FLOAT,
	[TotAsNum] INT NOT NULL DEFAULT 0,
	[AsId] INT FOREIGN KEY REFERENCES AssignmentData(AsId) NOT NULL,
	[UserId] INT FOREIGN KEY REFERENCES UserData(UserId) NOT NULL,
)
